# Procedure status registration message

# Node name
string node_name

# The procedure status
ProcStatus[] proc_status_vec

---
# Response status, see ServiceResponseStatus for more information.
int8 response

# If response process failed, describe the reason.
string reason
