# Topic Device Registration

# The topic device info.
TopicDeviceInfo request

---
# Response status, see ServiceResponseStatus for more information.
int8 response

# If response process failed, describe the reason.
string reason
